"""
product_parser.py
-----------------
Everything this repo knows about Tokopedia. The engines know how to drive a
browser; this file knows what a Tokopedia page says.

Read this before changing anything here
=======================================

**There is no structured data on a listing page.** Measured on six live
captures, 2026-09-10: zero `application/ld+json` blocks, zero
`__NEXT_DATA__`, zero React-flight payload, zero Apollo state. The grid is
fetched by client-side GraphQL after load and exists only in the rendered
DOM. So the JSON-LD-first design the rest of this family uses has nothing to
be first about, and the URL-pattern path §4 calls a *fallback* is promoted to
primary because there is nothing above it.

A DETAIL page is different: it carries a serialised Apollo cache in an inline
`window.__cache = {…}`, and that is where the real product id, the exact sold
count and the review count live. `parse_product_page` reads it.

**Class names are content hashes and nothing may anchor on them.**

    <span class="+tnoqZhn89+NHUA43BpiJg==">Kopi Hitam Bubuk Robusta …</span>
    <span class="YZHqvX+8TVU2YltRC9S+oA==">Rp7.500</span>

Those are base64 CSS-module hashes; they change on every deploy. The April
2026 prototype in this repo's history anchored on the emotion equivalents and
on `data-testid="linkProductName"`, `linkProductPrice`, `linkProductShopName`
and friends — **every one of those field selectors is now gone**, zero
occurrences on either page kind. What survived five months is the URL
pattern, three container `data-testid`s, and the utility class `flip`.

So the reads here are deliberately TEXT-ORDER based inside a
structurally-scoped tile. That is unusual for this family and it is the right
trade on this site: the tile's reading order ("badge, title, price,
was-price, rating, sold, shop, location") is a design decision Tokopedia has
kept, while the class that wraps each of those is regenerated by a build.

**Two page kinds, two markups, two paginations.** See PAGE KINDS below. This
is amazon-scraper's situation, and the triage lives in `page_flow.py` as data
rather than as three copies of an if-chain across three engines.
"""

import copy
import json
import logging
import re
from typing import Dict, List, Optional, Sequence, Tuple
from urllib.parse import urlsplit, urlunsplit, parse_qsl, urlencode, urljoin

from bs4 import BeautifulSoup

from output_writer import Product, SOURCE_DEFAULT

logger = logging.getLogger("product_parser")


# ---------------------------------------------------------------------------
# Hosts
# ---------------------------------------------------------------------------
# Tokopedia is ONE storefront. Measured 2026-09-10 by fetching the same search
# URL through an Indonesian exit and a US exit: identical status, identical
# tile count, `<html lang="id">` both times, IDR prices both times, ship-to
# "Jakarta Pusat" both times, and **zero** price differences across the 68
# products both runs saw. There is no geo-redirect, no locale path prefix and
# no second currency.
#
# Which is why this repo has NO --country flag: there would be nothing for it
# to select, and a flag that can only disagree with the URL is worse than no
# flag. The `country-` segment of a Scraping Browser endpoint still matters
# for getting IN — see the README's access section — but not for what comes
# back.
HOSTS = ("tokopedia.com", "www.tokopedia.com")

# Hosts that look like they belong and do not. Refuse them WITH THE REASON:
# "is not a Tokopedia site" would be false for a Tokopedia subdomain that
# simply is not a storefront, and sends the reader hunting for a typo (§5).
UNSUPPORTED: Dict[str, str] = {
    "seller.tokopedia.com": "is Tokopedia's seller dashboard, which requires "
                            "a login and publishes no product pages",
    "gql.tokopedia.com":    "is Tokopedia's GraphQL endpoint, not a page — "
                            "this scraper drives a browser, not the API",
    "images.tokopedia.net": "is Tokopedia's image CDN",
    "www.tokopedia.net":    "is Tokopedia's asset domain, not the storefront",
    "mitra.tokopedia.com":  "is the Mitra Tokopedia agent app, a different "
                            "product with a different catalogue",
}

# Kept for compatibility with the family's shared engine code, which reads a
# locale-to-currency map. Tokopedia has exactly one of each, so this is a
# one-entry table rather than a mechanism.
LOCALE_CURRENCY = {"id": "IDR"}
CURRENCY = "IDR"


def site_host(url: str) -> Optional[str]:
    """The row's `source`: the bare hostname with `www.` stripped."""
    host = (urlsplit(url).hostname or "").lower()
    if not host:
        return None
    return host[4:] if host.startswith("www.") else host


def unsupported_reason(url: str) -> Optional[str]:
    """Why this URL cannot be scraped, or None if it can be."""
    host = (urlsplit(url).hostname or "").lower()
    if not host:
        return "has no hostname"
    if host in UNSUPPORTED:
        return UNSUPPORTED[host]
    if host in HOSTS:
        return None
    if host.endswith(".tokopedia.com") or host.endswith(".tokopedia.net"):
        return ("is a Tokopedia subdomain but not the storefront — this "
                "scraper reads www.tokopedia.com")
    return "is not a Tokopedia address"


def is_supported_host(url: str) -> bool:
    return unsupported_reason(url) is None


def locale_of(url: str) -> str:
    """Tokopedia serves one locale. Present so shared code has it to call."""
    return "id"


def host_currency(url: str) -> str:
    return CURRENCY


# ---------------------------------------------------------------------------
# PAGE KINDS
# ---------------------------------------------------------------------------
# The same site answers a listing request in two entirely different shapes,
# and nothing about one predicts the other.
#
#                     search                       category listing
#   URL               /search?st=product&q=…       /p/<cat>/<sub>[/<subsub>]
#   grid container    divSRPContentProducts        data-ssr=productsCategoryL2/L3SSR
#   tile marker       imgLeg-c, one per tile       divProductWrapper, one per tile
#   anchor            a bare <a href>, IS the tile a[data-testid=lnkProductContainer]
#   pagination        infinite scroll ONLY         ?page=N works
#   count header      dSRPSearchInfo               none
#
# And `/p/<slug>` with ONE segment is neither: it is a discovery HUB of
# banners and recommendation carousels. It has no grid, no imgLeg-c and no
# divProductWrapper, but it does carry ~39 product links from those
# carousels. A parser anchored on the URL pattern alone returns 39 rows of
# filler and reports success; scoping to the grid returns zero, which is
# exit 4 and correct. That is why every selector below is grid-scoped.
SELECTORS = {
    # Grid containers, most durable first. `data-ssr` is the server's own
    # render marker and `data-testid` the site's own test hook; both have
    # outlived the class hashes beside them.
    "search_grid": '[data-testid="divSRPContentProducts"], '
                   '[data-ssr="contentProductsSRPSSR"]',
    "category_grid": '[data-ssr="productsCategoryL2/L3SSR"]',
    # One per tile on its own page kind — the count is how we know the grid
    # painted, and it matched the number of distinct product URLs exactly on
    # every capture (95 = 95 = 95 on search, 65 = 65 on category).
    "search_tile_marker": '[data-testid="imgLeg-c"]',
    "category_anchor": 'a[data-testid="lnkProductContainer"]',
    "category_tile_marker": '[data-testid="divProductWrapper"]',
    # The shop name and the shop's city, in that order. `flip` is a utility
    # class (it mirrors text for RTL) rather than a content hash, and there
    # are exactly two of them per search tile — 190 across 95 tiles, no
    # exceptions.
    "shop_and_location": "span.flip",
    "search_info": '[data-testid="dSRPSearchInfo"]',
    "product_image": 'img[alt="product-image"]',
}

# How many product links mean "the grid rendered". Must be > 1: waiting for a
# single match resolves on an unrelated link long before the grid paints
# (§5). Tokopedia's first batch is 60 tiles, so this is comfortably low.
MIN_CARD_MATCHES = 4


# ---------------------------------------------------------------------------
# Prices
# ---------------------------------------------------------------------------
# IDR as Tokopedia writes it: "Rp7.500". Dot grouping, and **no minor unit in
# any of the 74 distinct prices** across the captures — not one comma.
#
# So this is the `1.234,56` convention with the decimals absent, and the
# family's "exactly three trailing digits means a thousands grouping" rule
# gives the right answer on every price seen (Rp7.500 → 7500, Rp1.800 →
# 1800, Rp180.800 → 180800). The comma branch is kept anyway: it costs
# nothing, and "no IDR price has cents" is a claim these six captures do not
# license.
_GROUP_SPACES = "    "   # NBSP, narrow NBSP, thin space, space
_AMOUNT = (r'\d{1,3}(?:[.' + _GROUP_SPACES + r']\d{3})+(?:,\d{1,2})?'
           r'|\d+(?:,\d{1,2})?')
_PRICE_RE = re.compile(r'Rp\s*(' + _AMOUNT + r')')

# Things that live INSIDE a tile and carry their own number, which is
# MediaMarkt's instalment line (§4) in a different costume:
#
#   "Hemat s.d  8% Pakai Bonus"   29 of 95 search tiles — a promo, not the
#                                 discount, and its percentage is not the
#                                 badge's
#   "Tambah ke Wishlist"          the label of a button inside the category
#                                 anchor; lands in the title if not removed
#
# Both are stripped from the tile's text before anything is read out of it.
_PROMO_RE = re.compile(r'Hemat\s+s\.?d\.?\s*[\d.,]+\s*%[^0-9]*', re.I)
_WISHLIST_RE = re.compile(r'Tambah ke Wishlist', re.I)
# Percentages come out before prices are matched, not after. A rejected match
# has still consumed the currency symbol, so filtering afterwards loses the
# real price too (§4).
_PCT_RE = re.compile(r'-?\s*\d{1,3}(?:[.,]\d+)?\s*%')


def _normalize_amount(raw: str) -> Optional[float]:
    """Turn a written amount into a number, honouring all three groupings.

    `1,234.56` · `1.234,56` · `1 234,56`, with the space form allowing NBSP,
    narrow NBSP and thin space — a rendered page uses a no-break variant so
    the number does not wrap, and missing them parses `1 234` as 234.
    """
    s = raw.strip()
    for sp in _GROUP_SPACES:
        if sp != " ":
            s = s.replace(sp, " ")
    s = s.replace(" ", ".")
    has_dot, has_comma = "." in s, "," in s
    if has_dot and has_comma:
        # Whichever separator comes LAST is the decimal point.
        dec = "," if s.rfind(",") > s.rfind(".") else "."
        s = s.replace("." if dec == "," else ",", "").replace(dec, ".")
    elif has_comma:
        head, _, tail = s.rpartition(",")
        # Exactly three trailing digits is a thousands grouping: no currency
        # has a three-digit subunit, so "1,234" is 1234.
        s = (head + tail) if len(tail) == 3 else s.replace(",", ".")
    elif has_dot:
        head, _, tail = s.rpartition(".")
        if len(tail) == 3:
            s = s.replace(".", "")
        # One dot with 1-2 trailing digits would be a decimal point, and is
        # left as such. No Tokopedia price has ever been seen written that
        # way; if one is, this reads it correctly rather than multiplying it
        # by a thousand.
    try:
        return float(s)
    except ValueError:
        return None


def _tile_text(node) -> str:
    """The tile's readable text with the known in-tile noise removed."""
    text = node.get_text(" ", strip=True)
    text = _WISHLIST_RE.sub(" ", text)
    text = _PROMO_RE.sub(" ", text)
    return re.sub(r"\s{2,}", " ", text).strip()


def prices_in(text: str) -> List[float]:
    """Every `Rp` amount in reading order, percentages removed first."""
    out: List[float] = []
    for m in _PRICE_RE.finditer(_PCT_RE.sub(" ", text)):
        val = _normalize_amount(m.group(1))
        if val is not None:
            out.append(val)
    return out


def _discount_from(price: Optional[float],
                   original_price: Optional[float]) -> Optional[float]:
    """The discount COMPUTED from the two prices, never read off the badge.

    Two reasons, both measured. Tokopedia prints the badge only above some
    threshold: two search tiles carry a strike price at 7% and 8% off with no
    badge at all, so computing recovers 88 of 95 rows where reading the badge
    recovers 86. And where both exist they agree — 0 mismatches over 1
    percentage point across all 86 — so there is nothing to be gained by
    trusting the printed one.

    None rather than 0 or a negative when the figures are not what they were
    taken for, so a canary can assert "no original_price at or below its
    price" and mean it.
    """
    if price is None or original_price is None:
        return None
    if original_price <= 0 or original_price <= price:
        return None
    return round((original_price - price) / original_price * 100, 2)


# ---------------------------------------------------------------------------
# Rating and the sold count
# ---------------------------------------------------------------------------
# The tile prints "4.7  100rb+ terjual" — the rating, then the number sold.
# `rb` is *ribu* (thousand), `jt` is *juta* (million), and the trailing `+`
# means the site has rounded DOWN: "100rb+" against a detail page's exact
# `countSold` of 207785 for the same product. So a listing-mode sold count is
# a floor and says so in its own column; the two modes' values are not
# comparable and `diff_runs.py` must not be handed both.
_SOLD_UNITS = {None: 1, "": 1, "rb": 1_000, "jt": 1_000_000}
_SOLD_RE = re.compile(r'([\d.,]+)\s*(rb|jt)?\s*(\+?)\s*terjual', re.I)

# The rating is matched only where a sold count FOLLOWS it, and that lookahead
# is load-bearing rather than tidy. A product with no reviews prints no
# rating, and then its sold count stands alone:
#
#     "KOPI SAIYO : 100% Robusta Rp30.000 5 terjual Galeri UMKM …"
#
# A looser pattern reads that 5 as a five-star rating on a product that has
# never been rated. One such tile in 190.
_RATING_RE = re.compile(
    r'(?<![\d.,])([0-5](?:[.,]\d)?)\s+(?=[\d.,]+\s*(?:rb|jt)?\+?\s*terjual)',
    re.I)


def rating_in(text: str) -> Optional[float]:
    m = _RATING_RE.search(text)
    if not m:
        return None
    try:
        return float(m.group(1).replace(",", "."))
    except ValueError:
        return None


def sold_in(text: str) -> Tuple[Optional[int], Optional[bool]]:
    """(units sold, whether that figure is a floor). (None, None) if absent."""
    m = _SOLD_RE.search(text)
    if not m:
        return None, None
    n = _normalize_amount(m.group(1))
    if n is None:
        return None, None
    unit = (m.group(2) or "").lower() or None
    is_floor = bool(m.group(2)) or m.group(3) == "+"
    return int(n * _SOLD_UNITS[unit]), is_floor


# ---------------------------------------------------------------------------
# URLs, ids and pagination
# ---------------------------------------------------------------------------
# A product lives at /{shop-slug}/{product-slug}. Most product slugs end in a
# 19-digit tail and it is TEMPTING to make that the sku — but it is not the
# product id and it is not always there.
#
#   * The real id is `pdpBasicInfo.productID` in a detail page's Apollo cache:
#     103490518624 for a product whose URL tail is 1731177319241910164.
#   * 4 of 40 listing URLs carry no tail at all, and two of those carry a
#     short hex suffix instead (`-c69d`, `-71e1e`). All four are ordinary
#     organic products with byte-identical tile markup.
#
# So `sku` is the URL PATH — always present, stable, and what the site's own
# canonical uses. The numeric id, where a detail page states it, goes in its
# own column.
_PRODUCT_PATH_RE = re.compile(r'^/(?P<shop>[^/?#]+)/(?P<slug>[^/?#]+)$')
_SLUG_TAIL_RE = re.compile(r'-(\d{15,22})$')

# First path segments that are Tokopedia's own routes rather than a shop.
# A two-segment path under any of these is not a product, and letting one
# through is how a junk link steals a real product's row (§4).
_NOT_A_SHOP = frozenset("""
    search p find discovery promo help about register login deals now mall c
    blog career affiliate mitra seller review order cart checkout wishlist
    official-store rewards play flight kereta-api events pesan-antar
    tokopedia-care contact-us privacy terms bantuan how-to-shop
    """.split())

# Query parameters that identify the visit rather than the page. Stripped
# before a URL becomes a row's `url` or is compared to a canonical, because a
# detail page's own canonical arrives with a UTM tail
# (?utm_source=google&utm_medium=organic&utm_campaign=pdp) and a listing
# anchor arrives with an extParam carrying the search id — so two views of
# one product never join unless both sides are cleaned.
TRACKING_PARAMS = frozenset("""
    extParam utm_source utm_medium utm_campaign utm_term utm_content
    src search_id keyword whid aff_unique_id trkid ref refer
    navsource srp_component_id srp_page_id srp_page_title
    """.split())


def strip_tracking(url: str) -> str:
    parts = urlsplit(url)
    kept = [(k, v) for k, v in parse_qsl(parts.query, keep_blank_values=True)
            if k not in TRACKING_PARAMS]
    return urlunsplit((parts.scheme, parts.netloc, parts.path,
                       urlencode(kept), ""))


def product_path(href: str, base_url: str = "") -> Optional[str]:
    """The `/{shop}/{slug}` path of a product link, or None if it is not one."""
    if not href:
        return None
    absolute = urljoin(base_url or "https://www.tokopedia.com/", href)
    parts = urlsplit(absolute)
    host = (parts.hostname or "").lower()
    if host and host not in HOSTS:
        return None
    path = parts.path.rstrip("/")
    m = _PRODUCT_PATH_RE.match(path)
    if not m or m.group("shop").lower() in _NOT_A_SHOP:
        return None
    return path


def sku_from_url(url: str) -> Optional[str]:
    return product_path(url)


def shop_from_url(url: str) -> Optional[str]:
    path = product_path(url)
    return path.split("/")[1] if path else None


def slug_tail_id(url: str) -> Optional[str]:
    """The 19-digit tail on a product slug, where there is one.

    NOT the product id — see the note above `_PRODUCT_PATH_RE`. Exposed
    because it is a real identifier the site puts in its own URLs, and
    because naming it makes it harder for a future edit to mistake it for
    `product_id`.
    """
    path = product_path(url)
    if not path:
        return None
    m = _SLUG_TAIL_RE.search(path)
    return m.group(1) if m else None


_SEARCH_PATHS = ("/search",)
_CATEGORY_PREFIX = "/p/"


def listing_kind(url: str) -> str:
    """"search" · "category" · "hub" · "product" · "unknown"."""
    path = urlsplit(url).path.rstrip("/") or "/"
    if any(path == p or path.startswith(p + "/") for p in _SEARCH_PATHS):
        return "search"
    if path.startswith(_CATEGORY_PREFIX):
        segments = [s for s in path[len(_CATEGORY_PREFIX):].split("/") if s]
        # One segment is a discovery hub with no grid on it; two or more is a
        # real listing. Measured: /p/makanan-minuman has 0 tiles,
        # /p/makanan-minuman/minuman/kopi-bubuk has 65.
        return "category" if len(segments) >= 2 else "hub"
    if product_path(path):
        return "product"
    return "unknown"


# Category listings paginate with `?page=N`. Search does NOT, and the
# difference is the whole reason this is a function rather than a constant —
# two page kinds on one site using different conventions is amazon-scraper's
# `?page=` versus `?pg=` all over again.
PAGE_PARAM = "page"
PAGINATED_KINDS = ("category",)


def paginates_by_url(url: str) -> bool:
    """Whether page N of this listing has an address of its own.

    False for search, and that is measured rather than assumed. A fully
    scrolled search page publishes **no** `href` containing `page=`, no
    `link[rel=next]`, and no next-page button — every button on it is a
    filter or a sort. And appending `?page=2` does not paginate, it EMPTIES
    the result set: the page comes back with `Oops, produk nggak ditemukan`
    ("product not found"), no grid and no prices.

    That last part is the dangerous one. A `page_url()` that built `?page=N`
    unconditionally would fetch that empty page, find no new sku, conclude
    the listing was exhausted, and report a COMPLETE run holding page 1 —
    the silent-single-page failure of §7 arriving by a different route. So
    the engines must ask this before they plan page URLs.
    """
    return listing_kind(url) in PAGINATED_KINDS


def page_url(url: str, page_num: int) -> Optional[str]:
    """The address of page `page_num`, or None if the listing has none.

    Replaces an existing `page` rather than appending a second one, and
    preserves every other query parameter — the filters and the sort are
    what make a listing worth paginating.
    """
    if page_num <= 1:
        return strip_tracking(url)
    if not paginates_by_url(url):
        return None
    parts = urlsplit(strip_tracking(url))
    params = [(k, v) for k, v in parse_qsl(parts.query, keep_blank_values=True)
              if k != PAGE_PARAM]
    params.append((PAGE_PARAM, str(page_num)))
    return urlunsplit((parts.scheme, parts.netloc, parts.path,
                       urlencode(params), parts.fragment))


def page_number_from_url(url: str) -> int:
    for k, v in parse_qsl(urlsplit(url).query):
        if k == PAGE_PARAM:
            try:
                return max(1, int(v))
            except ValueError:
                return 1
    return 1


# ---------------------------------------------------------------------------
# Category
# ---------------------------------------------------------------------------
# A category comes from the URL on a category listing, and from the detail
# page's own breadcrumb otherwise — which is better than either, because it is
# the site's own classification rather than our reading of a path.
_NOT_A_CATEGORY = frozenset("""
    p search find discovery promo deals now mall
    """.split())


def category_from_url(url: str) -> Optional[str]:
    """The category slug a listing URL names, or None."""
    path = urlsplit(url).path.rstrip("/")
    if not path.startswith(_CATEGORY_PREFIX):
        return None
    segments = [s for s in path[len(_CATEGORY_PREFIX):].split("/")
                if s and s not in _NOT_A_CATEGORY]
    return "/".join(segments) or None


# ---------------------------------------------------------------------------
# Page state: served, refused, empty
# ---------------------------------------------------------------------------
# **This site gives a refusal no content to detect.** Every other site in
# this family answers a request it does not like with something — an Akamai
# reference, a DataDome shell, a branded error page under 403. Tokopedia, to
# an address it has scored badly, accepts the connection, completes TLS,
# opens the HTTP/2 stream and then resets it. Nothing arrives. curl reports
# exit 92, Chromium reports ERR_HTTP2_PROTOCOL_ERROR, and there is no page.
#
# So detection here is inverted: rather than looking for a marker a block
# page carries, look for a marker every REAL page carries and treat its
# absence as the signal. That is §8's `assets.mmsrg.com` trick, and
# Tokopedia's equivalent is its own asset host — present 3+ times on every
# one of the six captures, on every page kind, including the empty-result
# page.
_ASSET_MARKER = re.compile(r'tokopedia-static\.net|images\.tokopedia\.net', re.I)
_ASSET_MIN_MATCHES = 2

# Vendor challenge markers. Kept SHORT on purpose: none of these has ever
# been observed on this site, and every one that has not is a guess. The list
# exists because a bot manager can be switched on between deploys and a
# scraper that cannot name what stopped it is much harder to fix.
#
# Deliberately NOT included: `cf-turnstile`. The 2Captcha Scraping Browser's
# auto-solve extension injects a `cf-turnstile` hunter into every page it
# loads, so the marker appears on perfectly good pages fetched over
# --cdp-endpoint (§8). Adding it would need the extension-tag filter below
# to be exercised, and adding a marker whose only observed source is our own
# extension is how dead code spreads. The filter is applied anyway, so a
# future edit that broadens this list is already protected.
# Deliberately NOT included: the bare string "akamai". Tokopedia is fronted
# by Akamai, so its own performance-monitoring script references
# `…clientnsv4-s.akamaihd.net` on EVERY page — a live run of a /p/<slug> hub
# reported "Blocked by akamai" and exit 3 on a 191 KB page the site had
# plainly served. A marker that matches every page of the site it is meant to
# guard is worse than no marker. Akamai's actual REFUSAL strings are the two
# below, and those do not appear on a served page.
BOT_CHALLENGE_MARKERS = (
    "Request unsuccessful",       # Akamai's own refusal page
    "Reference #",                # ...and its reference line
    "g-recaptcha",
    "recaptcha/api.js",           # the loader
    "recaptcha/api2/anchor",      # a RENDERED widget's iframe
    "recaptcha/api2/bframe",      # ...and its challenge frame
    "data-sitekey",               # any vendor's widget, configured in markup
    "hcaptcha.com",
    "px-captcha",
    "_Incapsula_Resource",
)

# THE SITE'S OWN CAPTCHA MOUNT POINT, and it needs a structural check rather
# than a marker.
#
# Tokopedia ships `<captcha-widgets></captcha-widgets>` on EVERY page it
# serves — 13 of 13 dumps, including the empty-result page and a discovery
# hub — and its front-end config carries a reCAPTCHA sitekey
# (`"CAPTCHA_SITE_KEY":"6L…"`). So the machinery is present and configured
# everywhere, and NOTHING was ever rendered into it: no challenge of any kind
# appeared on any capture or any live run.
#
# That makes the bare tag useless as a marker — matching it would report a
# challenge on every page, which is the mistake the bare string "akamai"
# already made here once. What IS a signal is the element having CONTENT.
_WIDGET_MOUNT_RE = re.compile(
    r'<captcha-widgets\b[^>]*>(?P<body>.*?)</captcha-widgets\s*>',
    re.I | re.S)


def captcha_widget_is_populated(html: str) -> bool:
    """Whether the site's own `<captcha-widgets>` mount point has anything in it.

    Empty on every page Tokopedia has ever been observed serving. If it ever
    has children, the site has rendered a challenge into it — and that is
    worth knowing even when the child carries none of the vendor markers
    above, which a bare `data-sitekey` div would not.
    """
    for m in _WIDGET_MOUNT_RE.finditer(html or ""):
        if m.group("body").strip():
            return True
    return False

_EXTENSION_TAG_RE = re.compile(
    r'<script\b[^>]*\bsrc\s*=\s*["\'](?:chrome|moz)-extension://[^"\']*["\'][^>]*>'
    r'(?:\s*</script>)?', re.I)


def _strip_extension_tags(html: str) -> str:
    """Remove browser-extension script tags before looking for markers.

    The Scraping Browser API ships an auto-solve extension that injects its
    own captcha hunters into every page. Its markup mentions the vendors it
    hunts, so a marker scan over the raw HTML can report a challenge on a
    1.8 MB page holding the full catalogue — which is exactly what happened
    on mediamarkt-scraper's first live run.
    """
    return _EXTENSION_TAG_RE.sub(" ", html)


# The empty-result page, which is a SUCCESS and not a block: Tokopedia
# answers 200 with its filter rail, its footer and this sentence where the
# grid would be. Seen on `?page=2` of a search URL and on any query with no
# matches.
_NO_RESULTS_MARKERS = (
    "produk nggak ditemukan",
    "produk tidak ditemukan",
    "Coba kata kunci lain",
)


def detect_bot_challenge(html: str, url: str = "") -> Optional[str]:
    """The name of a challenge vendor found in the markup, or None.

    Broad on purpose (§8): different geos and different scenarios surface
    different challenges, and a detection is only a warning unless the page
    also has no products on it.
    """
    if not html:
        return None
    cleaned = _strip_extension_tags(html)
    lowered = cleaned.lower()
    for marker in BOT_CHALLENGE_MARKERS:
        if marker.lower() in lowered:
            return marker
    # The site's own mount point, checked structurally rather than as a
    # substring — see `captcha_widget_is_populated`.
    if captcha_widget_is_populated(cleaned):
        return "captcha-widgets"
    return None


def served_by_tokopedia(html: str) -> bool:
    """Whether this markup is a page Tokopedia itself built.

    A served page is assembled out of the site's own assets; an interstitial
    is not. Measured over all six captures: 2 or more matches on every real
    page including the empty-result one.
    """
    if not html:
        return False
    return len(_ASSET_MARKER.findall(html)) >= _ASSET_MIN_MATCHES


def is_no_results(html: str) -> bool:
    return any(m.lower() in html.lower() for m in _NO_RESULTS_MARKERS)


def detect_page_state(html: str, status: Optional[int] = None,
                      url: str = "") -> str:
    """One of "content" · "empty" · "blocked" · "challenge" · "unknown".

    The engines must not each re-derive this: three copies of the triage
    across three engines drift, and the drift is silent — one engine
    reporting exit 3 where its twin reports exit 0 on the same page. The
    retry/solve/blocked decision that follows from this verdict lives in
    `page_flow.STATE_POLICY` as data.
    """
    if status is not None and status != 200:
        # A non-200 from this host is a refusal; it has never been observed
        # carrying a page worth parsing.
        return "blocked"
    if not html or not html.strip():
        return "blocked"
    # THE NO-RESULTS SENTENCE COMES FIRST, before the asset threshold, and
    # the ordering is the point. "Oops, produk nggak ditemukan" is the
    # site's OWN Indonesian copy — an unambiguous positive signal that
    # Tokopedia both served this page and has nothing to put on it — while
    # `served_by_tokopedia` is a heuristic with a threshold. Checked the
    # other way round, a minimal real page carrying one asset reference
    # instead of the measured 3-7 was reported as BLOCKED, which is exit 3
    # for a correct answer and sends the reader hunting for a proxy problem.
    if is_no_results(html):
        return "empty"
    if not served_by_tokopedia(html):
        # No asset-host references at all: whatever this is, Tokopedia did
        # not build it.
        return "blocked"
    challenge = detect_bot_challenge(html, url)
    soup = BeautifulSoup(html, "html.parser")
    if _grid_of(soup, listing_kind(url)) is not None and _count_tiles(soup, url):
        return "content"
    if listing_kind(url) == "product":
        # A detail page has no grid; what it has is a product. Treat the
        # page's own product markup as the content signal, so an engine in
        # --mode product is not told "unknown" about a page it parsed fine.
        if _apollo_cache(html) or _meta_content(soup, "product:price:amount"):
            return "content"
    if listing_kind(url) == "hub":
        # A `/p/<slug>` discovery hub. It answers 200 with banners and
        # recommendation carousels and has no grid on it, so there is nothing
        # to parse and nothing wrong — "empty" rather than "unknown", so the
        # engines report exit 4 instead of retrying a page that will never
        # have products on it.
        return "empty"
    if challenge:
        return "challenge"
    return "unknown"


# ---------------------------------------------------------------------------
# Tiles
# ---------------------------------------------------------------------------
def _grid_of(soup, kind: str):
    if kind == "search":
        return soup.select_one(SELECTORS["search_grid"])
    if kind == "category":
        return soup.select_one(SELECTORS["category_grid"])
    # An unknown URL shape: try both, search first.
    return (soup.select_one(SELECTORS["search_grid"])
            or soup.select_one(SELECTORS["category_grid"]))


def _tiles(soup, url: str) -> Tuple[str, List]:
    """(page kind actually found, the tiles) — grid-scoped, always.

    Scoping is not a nicety here. `/p/<slug>` hubs and the "cheaper
    products" carousel that appears on every category page both hold product
    links: page 1 and page 2 of one category shared exactly 3 products, and
    all three were that carousel. Document-wide anchor collection would
    report them as real rows on both pages.
    """
    kind = listing_kind(url)
    grid = _grid_of(soup, kind)
    if grid is None:
        return "none", []

    search_tiles = [
        a for a in grid.select("a[href]")
        if product_path(a.get("href"), url)
        and a.select_one(SELECTORS["search_tile_marker"]) is not None
    ]
    if search_tiles:
        return "search", search_tiles

    cat_tiles = [
        a for a in grid.select(SELECTORS["category_anchor"])
        if product_path(a.get("href"), url)
        and a.select_one(SELECTORS["category_tile_marker"]) is not None
    ]
    if cat_tiles:
        return "category", cat_tiles
    return "none", []


def _count_tiles(soup, url: str) -> int:
    return len(_tiles(soup, url)[1])


def _without_image_block(tile):
    """A copy of the tile with the image container and its overlays removed.

    The discount badge and the "PreOrder" label are siblings of the image
    wrapper, so they sit BEFORE the title in reading order:

        94% Kopi Hitam Bubuk Robusta … Rp7.500 Rp120.000 …

    Stripping a leading percentage from the text would work on those and
    destroy a title that legitimately begins with one. Removing the image
    container structurally cannot: `imgLeg-c` is the site's own attribute and
    its parent is exactly the overlay group. Verified to leave a usable title
    on all 95 tiles of two captures, and to remove `45% PreOrder` from the
    two tiles that carry it.
    """
    clone = copy.copy(tile)
    marker = clone.select_one(SELECTORS["search_tile_marker"])
    if marker is not None and marker.parent is not None:
        marker.parent.decompose()
    return clone


def _title_of(tile, image_alt: Optional[str]) -> Optional[str]:
    """The product title: everything before the first price.

    Text-order rather than a selector, because the selector this would use
    (`span.+tnoqZhn89+NHUA43BpiJg==`) is a build hash and its predecessor
    (`data-testid="linkProductName"`) has already been deleted once. Reading
    order has outlived both.

    The image `alt` is the title verbatim on a category tile — checked
    against all 60, zero mismatches — so it is the cross-check and the
    fallback rather than the source.
    """
    body = _tile_text(_without_image_block(tile))
    head = re.split(r'Rp\s*\d', body, maxsplit=1)[0].strip(" -|·")
    if head and len(head) <= 300:
        return head
    if image_alt and image_alt != "product-image":
        return image_alt.strip() or None
    return head or None


# Images are the trap on this page, twice over, and both halves are the §10
# lesson: a column can be 100% populated and entirely wrong.
#
# **A tile holds several images and only one of them is the product.** A
# search tile carries 3 to 7 `<img>`: the product, a rating star, a "three
# dots" glyph, usually a shop badge, sometimes a "Beli Lokal" ribbon and a
# video thumbnail. Taking the first one that happens to sit on the site's CDN
# returns the SHOP BADGE for most rows — a populated column of
# `Power Merchant Pro.png`.
#
# **And the product image is lazy-loaded.** The browser fetches only what it
# has painted, so a tile below the fold carries a placeholder: 55 of 95
# search tiles held an SVG under `/obj/tokopedia-web-sg/zeus_v2/`, and 30 of
# 60 category tiles held a `data:` URI.
#
# So the product image is recognised POSITIVELY, by three things at once —
# it is the tile's own product `<img>`, it sits on the site's image CDN, and
# its path carries the `~tplv-` transform marker that every real product
# image has and no icon does. Everything else is null, which makes
# `image_url` honestly sparse rather than dishonestly complete: scroll
# further and more rows fill in.
_IMAGE_HOST_RE = re.compile(
    r'^https?://[^/]*(?:tokopedia-static\.net|images\.tokopedia\.net)/', re.I)
# Icons and chrome live under these path segments; product images never do.
_IMAGE_CHROME_RE = re.compile(r'/(?:obj|img)/', re.I)
# The CDN's image-transform marker, e.g.
# `…/ed86f8de…~tplv-aphluv4xwc-resize-jpeg:700:0.jpeg`.
_IMAGE_TRANSFORM_RE = re.compile(r'~tplv-', re.I)


def _product_img(tile):
    """The tile's product `<img>`, told apart from its icons.

    A search tile labels it `alt="product-image"` (95 of 95). A category tile
    does not label it at all — its `alt` IS the product title — but it holds
    exactly two images, the product first and the shop badge second, on all
    60 measured.
    """
    labelled = tile.select_one(SELECTORS["product_image"])
    if labelled is not None:
        return labelled
    imgs = tile.select("img")
    return imgs[0] if imgs else None


def _tile_image(tile) -> Optional[str]:
    img = _product_img(tile)
    if img is None:
        return None
    if img.get("data-li-lazy") is not None:
        return None           # the site's own "not loaded yet" marker
    src = (img.get("src") or "").strip()
    if not src or not _IMAGE_HOST_RE.match(src):
        return None
    if _IMAGE_CHROME_RE.search(src) or not _IMAGE_TRANSFORM_RE.search(src):
        return None
    return src


def _tile_image_alt(tile) -> Optional[str]:
    img = tile.select_one(SELECTORS["product_image"]) or tile.select_one("img[alt]")
    return img.get("alt") if img is not None else None


def _tile_shop(tile) -> Tuple[Optional[str], Optional[str]]:
    """(shop name, shop city) from the tile's two `span.flip` nodes.

    Exactly two per search tile, 190 across 95 tiles with no exceptions, in
    that order. A category tile has neither reliably, so both come back None
    there and the shop name falls back to the slug in the URL — which is the
    same seller by definition, just less pretty.
    """
    spans = [s.get_text(" ", strip=True) for s in
             tile.select(SELECTORS["shop_and_location"])]
    spans = [s for s in spans if s]
    if len(spans) >= 2:
        return spans[0], spans[1]
    if len(spans) == 1:
        return spans[0], None
    return None, None


def _category_tile_shop(tile) -> Optional[str]:
    """A category tile's shop name, from the badge image's `alt`.

    The shop badge's `alt` is the shop name — checked on all 60 tiles. Not
    the product image's, which is the product title, so the two have to be
    told apart by which one is NOT the title.
    """
    imgs = tile.select("img[alt]")
    if len(imgs) < 2:
        return None
    alt = (imgs[-1].get("alt") or "").strip()
    return alt or None


# ---------------------------------------------------------------------------
# Listing pages
# ---------------------------------------------------------------------------
def total_results(html: str, shown: int = 0) -> Optional[int]:
    """Tokopedia publishes no result total. Always None, and deliberately so.

    Its search header looks like it does:

        "Menampilkan 1 - 60 barang dari total  untuk "kopi""
        ("Showing 1 - 60 items of total ___ for "kopi"")

    but the total is EMPTY on every capture — `dari total` followed by
    nothing. The range is printed, and it is not an oracle either: after one
    scroll the header claimed 61-180 while the DOM held 95 tiles. So there is
    no arithmetic completeness check of the kind Amazon's published ranks
    allowed, and pretending otherwise would put a fabricated number in the
    sidecar.

    `shown` is accepted so the family's shared signature holds.
    """
    return None


def search_header(html: str) -> Optional[str]:
    """The raw result-count header, for the sidecar. Worth recording, worth
    nothing as a count — see `total_results`."""
    soup = BeautifulSoup(html, "html.parser")
    node = soup.select_one(SELECTORS["search_info"])
    if node is None:
        return None
    return re.sub(r"\s{2,}", " ", node.get_text(" ", strip=True)) or None


def total_pages(html: str) -> Optional[int]:
    """No page count is published either — there is no pagination markup at
    all on search, and a category listing prints no last-page number."""
    return None


def parse_products(html: str, url: str, page: int = 1,
                   category: Optional[str] = None) -> List[Product]:
    """Every product in the grid, in the order the site laid them out.

    One path, not two: there is no structured data to prefer. See the module
    docstring.
    """
    soup = BeautifulSoup(html, "html.parser")
    kind, tiles = _tiles(soup, url)
    if not tiles:
        return []

    cat = category or category_from_url(url)
    host = site_host(url) or SOURCE_DEFAULT
    rows: List[Product] = []

    for position, tile in enumerate(tiles, start=1):
        path = product_path(tile.get("href"), url)
        if not path:
            continue
        text = _tile_text(tile)
        prices = prices_in(text)
        price = prices[0] if prices else None
        original = prices[1] if len(prices) > 1 else None
        sold, sold_is_floor = sold_in(text)
        alt = _tile_image_alt(tile)

        if kind == "search":
            shop, location = _tile_shop(tile)
        else:
            shop, location = _category_tile_shop(tile), None

        rows.append(Product(
            source=host,
            url=strip_tracking(urljoin(url, tile.get("href") or "")),
            sku=path,
            title=_title_of(tile, alt),
            brand=shop or path.split("/")[1],
            price=price,
            # A fact on this site, not a guess: one storefront, one currency,
            # measured identical from two exit countries. It still comes from
            # the symbol `Rp` rather than from structured data, which is why
            # `price_source` says "dom" and not more.
            currency=CURRENCY if price is not None else None,
            original_price=original,
            discount_pct=_discount_from(price, original),
            rating=rating_in(text),
            review_count=None,      # never on a tile; --mode product has it
            in_stock=None,          # never stated on a tile
            image_url=_tile_image(tile),
            category=cat,
            price_source="dom",
            page=page,
            position=position,
            shop_slug=path.split("/")[1],
            shop_location=location,
            sold=sold,
            sold_is_floor=sold_is_floor,
            slug_id=slug_tail_id(path),
        ))

    _report_coverage(rows, kind, url)
    return rows


# Below these shares something is wrong with the read rather than with the
# page, and a warning naming the number is what turned two silent regressions
# in this family into five-minute fixes. The thresholds differ by page kind
# because the pages genuinely differ: a category tile prints no rating and no
# was-price at all.
_COVERAGE_FLOORS = {
    "search":   {"price": 0.98, "title": 0.98, "rating": 0.95, "brand": 0.98},
    "category": {"price": 0.95, "title": 0.95, "brand": 0.90},
}


def _report_coverage(rows: Sequence[Product], kind: str, url: str) -> None:
    if not rows:
        return
    floors = _COVERAGE_FLOORS.get(kind, {})
    total = len(rows)
    for field, floor in floors.items():
        got = sum(1 for r in rows if getattr(r, field, None) is not None)
        share = got / total
        if share < floor:
            logger.warning(
                "%s coverage %.0f%% (%d/%d) on a %s page, below the %.0f%% "
                "this site normally gives — the markup may have changed: %s",
                field, share * 100, got, total, kind, floor * 100, url)
    imgs = sum(1 for r in rows if r.image_url)
    logger.info("parsed %d products from a %s page (%d with a loaded image; "
                "images below the fold are placeholders until scrolled)",
                total, kind, imgs)


# ---------------------------------------------------------------------------
# Detail pages: the Apollo cache
# ---------------------------------------------------------------------------
# A detail page carries no JSON-LD either, but it does carry a serialised
# Apollo cache in an inline script:
#
#     window.__cache = {"ROOT_QUERY":{…},"pdpBasicInfo103490518624":{…},…}
#
# That is structured data even though it is not schema.org, and it is the
# primary path for --mode product. What it holds, measured:
#
#     pdpBasicInfo<id>   productID, alias, shopID, shopName, url, condition,
#                        status, weight/weightUnit, minOrder/maxOrder,
#                        createdAt, category ->
#     pdpCategory<id>    name, breadcrumbURL
#     $pdpBasicInfo<id>.stats     rating, countReview
#     $pdpBasicInfo<id>.txStats   countSold (EXACT), itemSoldFmt
#
# The price is NOT in it — that comes from a meta tag, below.
_CACHE_RE = re.compile(r'window\.__cache\s*=\s*')


def _apollo_cache(html: str) -> Optional[dict]:
    """The page's Apollo cache as a dict, or None.

    Brace-matched rather than regexed to the end: the object is 67 KB of
    nested JSON with escaped quotes throughout, and a greedy pattern picks up
    whatever script follows it.
    """
    m = _CACHE_RE.search(html or "")
    if not m:
        return None
    start = m.end()
    if start >= len(html):
        return None
    if html[start] == '"':
        # Some builds emit it as a JSON string literal holding JSON.
        i = start + 1
        while i < len(html):
            if html[i] == "\\":
                i += 2
                continue
            if html[i] == '"':
                break
            i += 1
        try:
            return json.loads(json.loads(html[start:i + 1]))
        except (ValueError, TypeError):
            return None
    if html[start] != "{":
        return None
    depth, i, in_str, esc = 0, start, False, False
    while i < len(html):
        ch = html[i]
        if in_str:
            if esc:
                esc = False
            elif ch == "\\":
                esc = True
            elif ch == '"':
                in_str = False
        elif ch == '"':
            in_str = True
        elif ch == "{":
            depth += 1
        elif ch == "}":
            depth -= 1
            if depth == 0:
                break
        i += 1
    try:
        return json.loads(html[start:i + 1])
    except ValueError:
        return None


_BASIC_INFO_RE = re.compile(r'^pdpBasicInfo(\d+)$')


def _basic_info(cache: dict) -> Tuple[Optional[str], Optional[dict]]:
    for key, value in (cache or {}).items():
        m = _BASIC_INFO_RE.match(key)
        if m and isinstance(value, dict):
            return m.group(1), value
    return None, None


def _cache_ref(cache: dict, node, field: str) -> Optional[dict]:
    """Follow one Apollo reference — `{"type":"id","id":"pdpCategory2787"}`."""
    ref = (node or {}).get(field)
    if isinstance(ref, dict) and isinstance(ref.get("id"), str):
        target = cache.get(ref["id"])
        return target if isinstance(target, dict) else None
    return None


# The price, and the one thing on this page that looks like structured data
# and is not quite:
#
#     <meta property="product:price:amount"   content="7500">
#     <meta property="product:price:currency" content="Rp">
#
# 7500 matched the tile's `Rp7.500` exactly, so this is a genuine SECOND view
# of the price and is what makes `price_source` mean something in this mode.
#
# `Rp` is a SYMBOL, not an ISO 4217 code. §4's tier-2 rule is a written code
# checked against an allowlist of real codes; handing that allowlist the
# string "Rp" and asking what it thinks is how a size chart becomes a
# currency. It is mapped through a symbol table instead.
_SYMBOL_TO_ISO = {"rp": "IDR", "idr": "IDR"}


def _meta_content(soup, *names: str) -> Optional[str]:
    for name in names:
        for attr in ("property", "name", "itemprop"):
            node = soup.find("meta", attrs={attr: name})
            if node is not None and node.get("content"):
                return node["content"].strip()
    return None


def _to_int(value) -> Optional[int]:
    try:
        return int(str(value).strip())
    except (TypeError, ValueError):
        return None


def _to_float(value) -> Optional[float]:
    try:
        return float(str(value).strip().replace(",", "."))
    except (TypeError, ValueError):
        return None


# The detail page's title, and this one is worth spelling out because three
# of the four obvious sources are wrong:
#
#   <h1>                       "Kopi Hitam Bubuk Robusta …"                 exact
#   lblPDPProductNameJumper    the same string                              exact
#   og:title / twitter:title   "Promo Kopi Hitam … di Zayn Snack | Tokopedia"
#   <title>                    "Promo Kopi Hitam … - Kab. Magetan - Zayn Snack | Tokopedia"
#
# The meta tags carry a "Promo " prefix the product's name does not have and
# a " di {shop} | Tokopedia" suffix, and stripping those with a regex is
# guesswork about a marketing string. The `<h1>` is the product name as the
# page renders it, and the site's own test hook agrees with it byte for byte.
_TITLE_JUMPER = '[data-testid="lblPDPProductNameJumper"]'
_TITLE_META_PREFIX = re.compile(r'^(?:Promo|Jual)\s+(?=\S)')


def _detail_title(soup, shop_name: Optional[str]) -> Optional[str]:
    for selector in (_TITLE_JUMPER, "h1"):
        node = soup.select_one(selector)
        if node is not None:
            text = node.get_text(" ", strip=True)
            if text:
                return text
    # Last resort: the meta title with its two decorations removed. Only
    # reached if the page rendered no h1 at all, which no capture has done.
    raw = (_meta_content(soup, "og:title", "twitter:title") or "").strip()
    if not raw:
        return None
    raw = _TITLE_META_PREFIX.sub("", raw)
    raw = re.sub(r'\s*\|\s*Tokopedia\s*$', "", raw)
    if shop_name:
        raw = re.sub(r'\s+di\s+' + re.escape(shop_name) + r'\s*$', "", raw)
    return raw.strip() or None


# The seller's city on a detail page, which only the `<title>` states:
#
#     "Promo {product} - Kab. Magetan - Zayn Snack | Tokopedia"
#
# Split on the shop name we already have from the Apollo cache rather than on
# position, so a product name containing " - " cannot shift the answer, and
# return None unless the shape is exactly right. A guessed city is worse than
# no city (§8).
def _detail_shop_location(soup, shop_name: Optional[str]) -> Optional[str]:
    if not shop_name or soup.title is None:
        return None
    raw = (soup.title.string or "").strip()
    marker = " - " + shop_name
    if not raw.endswith(marker + " | Tokopedia"):
        return None
    head = raw[:-len(marker + " | Tokopedia")]
    _, sep, city = head.rpartition(" - ")
    if not sep or not city.strip() or len(city) > 60:
        return None
    return city.strip()


def parse_product_page(html: str, url: str,
                       category: Optional[str] = None) -> Optional[Product]:
    """One product from its own page: Apollo cache first, meta tags for price.

    Returns None when the page is not a product page — which is a real case
    and not a fault: a shop front and a hub both answer 200 and neither has a
    `pdpBasicInfo` node.
    """
    soup = BeautifulSoup(html or "", "html.parser")
    cache = _apollo_cache(html) or {}
    product_id, basic = _basic_info(cache)

    price = _to_float(_meta_content(soup, "product:price:amount"))
    raw_currency = _meta_content(soup, "product:price:currency")
    currency = _SYMBOL_TO_ISO.get((raw_currency or "").strip().lower())
    if price is not None and currency is None:
        # The page stated a price without a currency this table knows. Never
        # default it (§8): say nothing rather than claim IDR.
        logger.warning("unrecognised currency %r on %s — leaving it null",
                       raw_currency, url)

    canonical = soup.select_one('link[rel="canonical"]')
    row_url = strip_tracking(
        (basic or {}).get("url")
        or (canonical.get("href") if canonical is not None else None)
        or url)

    if basic is None and price is None:
        return None

    stats = _cache_ref(cache, basic, "stats") or {}
    tx_stats = _cache_ref(cache, basic, "txStats") or {}
    cat_node = _cache_ref(cache, basic, "category") or {}

    sold = _to_int(tx_stats.get("countSold"))
    status = (basic or {}).get("status")
    max_order = _to_int((basic or {}).get("maxOrder"))
    in_stock = None
    if status:
        in_stock = status == "ACTIVE" and (max_order is None or max_order > 0)

    shop_name = (basic or {}).get("shopName") or None
    title = _detail_title(soup, shop_name)

    path = product_path(row_url) or product_path(url)
    return Product(
        source=site_host(row_url) or SOURCE_DEFAULT,
        url=row_url,
        sku=path,
        title=title,
        brand=(basic or {}).get("shopName") or (path.split("/")[1] if path else None),
        price=price,
        currency=currency if price is not None else None,
        # A detail page carries no strikethrough of its own, and the "similar
        # products" carousel's prices belong to other products (§4). Null
        # rather than a neighbour's number.
        original_price=None,
        discount_pct=None,
        rating=_to_float(stats.get("rating")),
        review_count=_to_int(stats.get("countReview")),
        in_stock=in_stock,
        image_url=(basic or {}).get("defaultMediaURL") or None,
        category=cat_node.get("name") or category or None,
        # The price came from a meta tag and the rest from the page's own
        # Apollo cache. Named for what it is rather than borrowing the
        # family's "jsonld" label for something that is not JSON-LD.
        price_source="meta+apollo" if basic else "meta",
        page=None,
        position=None,
        shop_slug=path.split("/")[1] if path else None,
        shop_location=_detail_shop_location(soup, shop_name),
        # EXACT here, where a tile's is a floor — 207785 against the tile's
        # "100rb+" for the same product. The two are not comparable and
        # `sold_is_floor` is what says so.
        sold=sold,
        sold_is_floor=False if sold is not None else None,
        slug_id=slug_tail_id(row_url),
        product_id=product_id,
        shop_id=(basic or {}).get("shopID") or None,
        condition=((basic or {}).get("condition") or "").title() or None,
        weight_grams=_weight_grams(basic),
        stock_max=max_order,
        listed_at=(basic or {}).get("createdAt") or None,
        category_url=strip_tracking(cat_node.get("breadcrumbURL") or "") or None,
    )


_WEIGHT_TO_GRAMS = {"GRAM": 1, "GRAMS": 1, "KILOGRAM": 1000, "KG": 1000}


def _weight_grams(basic: Optional[dict]) -> Optional[int]:
    """The shipping weight in grams, so one column holds one unit.

    The site states a number and a unit separately (`weight: 1`,
    `weightUnit: "KILOGRAM"`), and a column mixing grams with kilograms would
    be a number nobody can compare.
    """
    if not basic:
        return None
    value = _to_float(basic.get("weight"))
    unit = str(basic.get("weightUnit") or "").upper()
    if value is None or unit not in _WEIGHT_TO_GRAMS:
        return None
    return int(round(value * _WEIGHT_TO_GRAMS[unit]))


def shop_metadata(html: str, url: str) -> Dict[str, Optional[str]]:
    """The seller's own facts, for the sidecar of a run that covers one shop.

    Read from the same Apollo cache. A run covers exactly one shop, so these
    would produce an output file holding a single line if they were a row —
    and they cannot be attached to a product row without claiming they
    describe the product.
    """
    cache = _apollo_cache(html) or {}
    _, basic = _basic_info(cache)
    if not basic:
        return {}
    return {
        "shop_id": basic.get("shopID") or None,
        "shop_name": basic.get("shopName") or None,
        "shop_slug": shop_from_url(url),
    }
